#ifndef _KEYBOARD_
#define _KEYBOARD_


#define KEY_014 KEY_0
#define KEY_019 KEY_1
#define KEY_024 KEY_2
#define KEY_030 KEY_3
#define KEY_013 KEY_4
#define KEY_018 KEY_5
#define KEY_023 KEY_6
#define KEY_029 KEY_7
#define KEY_012 KEY_8
#define KEY_017 KEY_9
#define KEY_022 KEY_A
#define KEY_028 KEY_B
#define KEY_011 KEY_C
#define KEY_016 KEY_D
#define KEY_021 KEY_E
#define KEY_027 KEY_F
#define KEY_001 KEY_LEARN
#define KEY_006 KEY_IO_VIEW
#define KEY_002 KEY_RAM_VIEW
#define KEY_007 KEY_ROM_VIEW
#define KEY_003 KEY_AUTO_VIEW
#define KEY_004 KEY_BUS_TEST
#define KEY_005 KEY_ROM_TEST
#define KEY_008 KEY_RAMLONG_TEST
#define KEY_009 KEY_RAMSHORT_TEST
#define KEY_010 KEY_IO_TEST
#define KEY_025 KEY_PRIOR
#define KEY_031 KEY_MORE
#define KEY_015 KEY_ENTER_YES
#define KEY_020 KEY_CLEAR_NO
#define KEY_026 KEY_STS_CTL
#define KEY_032 KEY_READ_TS
#define KEY_038 KEY_WRITE_TS
#define KEY_033 KEY_RAMP
#define KEY_039 KEY_WALK
#define KEY_034 KEY_TOGGL_ADDR
#define KEY_040 KEY_TOGGL_DATA
#define KEY_035 KEY_CONT
#define KEY_036 KEY_REPEAT
#define KEY_037 KEY_LOOP
#define KEY_041 KEY_STOP
#define KEY_042 KEY_RUN_UUT
#define KEY_044 KEY_PROGRAM
#define KEY_052 KEY_LABEL
#define KEY_058 KEY_GOTO
#define KEY_045 KEY_IF
#define KEY_051 KEY_GR_THAN
#define KEY_057 KEY_EQUALS
#define KEY_047 KEY_AND
#define KEY_048 KEY_OR
#define KEY_053 KEY_SHIFT_LEFT
#define KEY_054 KEY_SHIFT_RIGHT
#define KEY_059 KEY_INCR
#define KEY_060 KEY_DECR
#define KEY_061 KEY_COMPL
#define KEY_050 KEY_EXEC
#define KEY_055 KEY_REG
#define KEY_049 KEY_READ_PROBE
#define KEY_062 KEY_READ_TAPE
#define KEY_063 KEY_WRITE_TAPE
#define KEY_064 KEY_SYNC
#define KEY_043 KEY_SETUP
#define KEY_046 KEY_DISPL
#define KEY_056 KEY_AUX_IF
#define KEY_065 KEY_HIGH
#define KEY_066 KEY_LOW

#define KEY_0              0
#define KEY_1              1
#define KEY_2              2
#define KEY_3              3
#define KEY_4              4
#define KEY_5              5
#define KEY_6              6
#define KEY_7              7
#define KEY_8              8
#define KEY_9              9
#define KEY_A             10
#define KEY_B             11
#define KEY_C             12
#define KEY_D             13
#define KEY_E             14
#define KEY_F             15
#define KEY_LEARN         16
#define KEY_IO_VIEW       18
#define KEY_RAM_VIEW      17
#define KEY_ROM_VIEW      19
#define KEY_AUTO_VIEW     20
#define KEY_BUS_TEST      21
#define KEY_ROM_TEST      22
#define KEY_RAMLONG_TEST  23
#define KEY_RAMSHORT_TEST 24
#define KEY_IO_TEST       25
#define KEY_PRIOR         26
#define KEY_MORE          27
#define KEY_ENTER_YES     28
#define KEY_CLEAR_NO      29
#define KEY_STS_CTL       30
#define KEY_READ_TS       31
#define KEY_WRITE_TS      32
#define KEY_RAMP          33
#define KEY_WALK          34
#define KEY_TOGGL_ADDR    35
#define KEY_TOGGL_DATA    36
#define KEY_CONT          37
#define KEY_REPEAT        38
#define KEY_LOOP          39
#define KEY_STOP          40
#define KEY_RUN_UUT       41
#define KEY_PROGRAM       42
#define KEY_LABEL         43
#define KEY_GOTO          44
#define KEY_IF            45
#define KEY_GR_THAN       46
#define KEY_EQUALS        47
#define KEY_AND           48
#define KEY_OR            49
#define KEY_SHIFT_LEFT    50
#define KEY_SHIFT_RIGHT   51
#define KEY_INCR          52
#define KEY_DECR          53
#define KEY_COMPL         54
#define KEY_EXEC          55
#define KEY_REG           56
#define KEY_READ_PROBE    57
#define KEY_READ_TAPE     58
#define KEY_WRITE_TAPE    59
#define KEY_SYNC          60
#define KEY_SETUP         61
#define KEY_DISPL         62
#define KEY_AUX_IF        63
#define KEY_HIGH          64
#define KEY_LOW           65

#endif
